<script setup lang="ts">
import { nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import * as echarts from 'echarts'
import type { Target, TrendRange, MetricKey } from '../types'
const props=defineProps<{target:Target;trend:any;range:TrendRange;metric:MetricKey;mode:'growth'|'total'}>()
const emit=defineEmits<{(e:'update:range',value:TrendRange):void;(e:'update:metric',value:MetricKey):void;(e:'update:mode',value:'growth'|'total'):void}>()
const chartEl=ref<HTMLElement|null>(null);let chart:any
const metrics=()=>props.target.target_type==='video'?[['view_count','播放量'],['like_count','点赞'],['coin_count','投币'],['favorite_count','收藏'],['reply_count','评论'],['danmaku_count','弹幕'],['online_count','在线']]:[['follower_count','粉丝'],['video_count','投稿'],['following_count','关注']]
const fmt=(value:number)=>Math.abs(value)>=10000?`${(value/10000).toFixed(1)}万`:Math.abs(value)>=1000?`${(value/1000).toFixed(1)}千`:String(Math.round(value))
function draw(){if(!chartEl.value||!props.trend?.points?.length)return;chart?.dispose();chart=echarts.init(chartEl.value);const points=props.trend.points;const key=props.metric;const values=points.map((p:any)=>props.mode==='growth'?(p[key]==null?null:(p[key]||0)-(points[0][key]||0)):p[key]);chart.setOption({animationDuration:350,tooltip:{trigger:'axis',formatter:(items:any[])=>{const item=items[0];const raw=points[item.dataIndex]?.[key];return `${item.axisValue}<br/>${item.seriesName}：${fmt(Number(item.value))}<br/>原始值：${fmt(Number(raw))}`}},grid:{left:58,right:24,top:22,bottom:38},xAxis:{type:'category',boundaryGap:false,data:points.map((p:any)=>new Date(p.time).toLocaleDateString('zh-CN',{month:'2-digit',day:'2-digit'}))},yAxis:{type:'value',name:props.mode==='growth'?'增长':'总量',axisLabel:{formatter:fmt},splitLine:{lineStyle:{color:'#edf1f6'}}},series:[{name:metrics().find(x=>x[0]===key)?.[1]||key,type:'line',smooth:.25,showSymbol:points.length<20,lineStyle:{width:3,color:'#3478e5'},itemStyle:{color:'#3478e5'},areaStyle:{color:'rgba(52,120,229,.08)'},data:values}]})}
watch(()=>[props.trend,props.metric,props.mode],async()=>{await nextTick();draw()},{deep:true});onMounted(draw);onUnmounted(()=>chart?.dispose())
</script>
<template><section class="trend-panel"><div class="trend-head"><div><span class="eyebrow">ANALYTICS</span><h2>趋势分析</h2><p>{{trend?.points?.length||0}} 个采样点 · {{mode==='growth'?'相对窗口首点的增长':'平台返回的绝对值'}}</p></div><div class="trend-actions"><div class="segmented"><button v-for="option in ([24,168,720] as TrendRange[])" :key="option" :class="{chosen:range===option}" @click="emit('update:range',option)">{{option===24?'24小时':option===168?'7天':'30天'}}</button></div><div class="segmented"><button :class="{chosen:mode==='growth'}" @click="emit('update:mode','growth')">增量</button><button :class="{chosen:mode==='total'}" @click="emit('update:mode','total')">总量</button></div></div></div><div class="metric-tabs"><button v-for="([key,label]) in metrics()" :key="key" :class="{selected:metric===key}" @click="emit('update:metric',key as MetricKey)">{{label}}</button></div><div v-if="!trend?.points?.length" class="chart-empty"><div class="empty-chart-icon">⌁</div><strong>这个时间范围暂无历史数据</strong><span>系统采集成功后，趋势会自动出现在这里</span></div><div v-else-if="trend.points.length===1" class="chart-empty"><div class="empty-chart-icon">◷</div><strong>已记录当前值</strong><span>等待下一次采集后形成趋势曲线</span></div><div v-else ref="chartEl" class="chart"></div></section></template>
